In [2]:
import pandas as pd
import numpy as np
import matplotlib
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [3]:
Train = pd.read_csv("Train.csv")
Train.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
Test = pd.read_csv("Test.csv")
Test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
SS = pd.read_csv("sample_submission.csv")
SS.head()

   ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0

In [6]:
target = 'label'
IDcol = SS['ImageId']


def modelfit(alg,dtrain,dtest,predictors,target,IDcol,filename):
    from sklearn.metrics import confusion_matrix
    #fit the algorithm on the data
    alg.fit(dtrain[predictors],dtrain[target])
    
    #predict training set
    dtrain_predictions=alg.predict(dtrain[predictors])
    
    #Error Metrics
    confusion_matrix = confusion_matrix(dtrain[target], dtrain_predictions)
    print(confusion_matrix)
    
    #Accuracy
    print('Accuracy of classifier on train set: {:.2f}'.format(alg.score(dtrain[predictors],dtrain[target])))
    
    #predict test set
    dtest[target]=alg.predict(dtest[predictors])
       
    #Export Submission File:
#    IDcol.append(target)

    #submission=pd.DataFrame({x:dtest.Loan_Status[x] for x in IDcol})
    submission=pd.DataFrame(SS['ImageId'])
    submission['Label']=dtest[target]
    submission.to_csv(filename,index=False)

In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
#k = 5
X=Train.iloc[:,1:]
Y=Train.iloc[:,0]
X_tst=Test

alg1=DecisionTreeClassifier(max_depth=10, min_samples_leaf=60)
alg1.fit(X,Y)
Y_Trn=alg1.predict(X)
confusion_matrix = confusion_matrix(Y,Y_Trn)
print(confusion_matrix)
Y_Tst=alg1.predict(X_tst)

#Accuracy
print('Accuracy of classifier on train set: {:.2f}'.format(alg1.score(X,Y)))
#modelfit(alg1,train,test,predictors,target,IDcol,'res_DesTree.csv')
print(Y_Tst)

predictors=[x for x in Train.columns if x not in target]
alg1=DecisionTreeClassifier()
modelfit(alg1,train,test,predictors,target,IDcol,'res_digit_DesTree.csv')
#print('Predictors:',predictors)

[[3728   12   47   62   21   59   64   23   92   24]
 [   1 4370   55   62   23   34    8   24  102    5]
 [  93   76 3334  138   64   72   76   93  179   52]
 [  25   60  189 3434   48  170   30   83  202  110]
 [  44   17   71   66 3372   23   52   43  163  221]
 [  91   60   42  237   59 2791  120   93  179  123]
 [ 107   27  102   62   54  112 3529    9  112   23]
 [  28   48   92   53   62   24    2 3831  101  160]
 [  20  157  112  168   66  136   62   25 3156  161]
 [  40   21   55  104  164   43   11  143  116 3491]]
Accuracy of classifier on train set: 0.83
[2 0 9 ... 3 9 2]

In [31]:
#Desicion Tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
predictors=[x for x in Train.columns if x not in target]
alg1=DecisionTreeClassifier()
modelfit(alg1,Train,Test,predictors,target,IDcol,'res_digit_DesTree.csv')

[[4132    0    0    0    0    0    0    0    0    0]
 [   0 4684    0    0    0    0    0    0    0    0]
 [   0    0 4177    0    0    0    0    0    0    0]
 [   0    0    0 4351    0    0    0    0    0    0]
 [   0    0    0    0 4072    0    0    0    0    0]
 [   0    0    0    0    0 3795    0    0    0    0]
 [   0    0    0    0    0    0 4137    0    0    0]
 [   0    0    0    0    0    0    0 4401    0    0]
 [   0    0    0    0    0    0    0    0 4063    0]
 [   0    0    0    0    0    0    0    0    0 4188]]
Accuracy of classifier on train set: 1.00

In [32]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
predictors=[x for x in Train.columns if x not in target]
alg1=RandomForestClassifier()
modelfit(alg1,Train,Test,predictors,target,IDcol,'res_digit_RandomFst.csv')

[[4130    0    0    0    0    0    1    0    1    0]
 [   0 4683    1    0    0    0    0    0    0    0]
 [   0    1 4175    0    0    0    0    1    0    0]
 [   0    0    3 4345    0    0    0    2    1    0]
 [   0    0    0    1 4069    0    0    1    1    0]
 [   0    0    0    0    2 3790    0    0    2    1]
 [   1    0    0    0    0    0 4136    0    0    0]
 [   0    0    2    0    0    0    0 4397    0    2]
 [   0    1    1    1    1    1    1    0 4057    0]
 [   2    0    0    2    1    0    0    2    2 4179]]
Accuracy of classifier on train set: 1.00

In [ ]:
#SVM
from sklearn import svm
from sklearn.metrics import confusion_matrix
predictors=[x for x in Train.columns if x not in target]
alg1=svm.SVC(C=200,kernel='rbf',gamma=0.01,probability=False)
modelfit(alg1,Train,Test,predictors,target,IDcol,'res_digit_SVM.csv')

In [21]:
SS['Label']=Y_Tst
SS.to_csv('res_digit1.csv',index=False)

In [24]:
SS1=pd.read_csv('res_digit1.csv')
SS1.tail()

       ImageId  Label
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2